name: Build and Deploy Developer Website

on:
#   push:
#     branches: [r1-saas, v7.4]
#   repository_dispatch:
  workflow_dispatch:

jobs:
  trigger-remote-build-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch initiating repository event
       
        run: |
          curl -X POST ${{ vars.TARGET_REPO }} \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.USER_NAME }}:${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "initiate_deploy", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
